# Generated by Django 4.2.7 on 2023-12-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventticket_amount_expected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicketComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular Ticket"),
                            ("VIP", "VIP Ticket"),
                            ("VVIP", "VVIP Ticket"),
                            ("Children", "Children"),
                        ],
                        max_length=255,
                    ),
                ),
                ("number_of_tickets", models.IntegerField(default=1)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventticket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
