# Generated by Django 4.2.7 on 2023-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventticketcomponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("Single", "Single"), ("Multiple", "Multiple")], max_length=255
            ),
        ),
    ]
