# Generated by Django 4.2.7 on 2023-12-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketcomponent',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketcomponents', to='events.eventticket'),
        ),
    ]
