# Generated by Django 4.2.7 on 2024-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_eventticket_payment_link_eventticket_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="notif_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="payment_notif_send",
            field=models.BooleanField(default=False),
        ),
    ]
