# Generated by Django 4.2.7 on 2024-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_event_couples_ticket_price_event_group_ticket_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventticketcomponent",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular Ticket"),
                    ("VIP", "VIP Ticket"),
                    ("VVIP", "VVIP Ticket"),
                    ("Children", "Children"),
                    ("Student", "Student"),
                    ("Couple", "Couple"),
                    ("Group", "Group"),
                ],
                max_length=255,
            ),
        ),
    ]
