# Generated by Django 4.2.7 on 2024-02-07 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_eventticketcomponent_ticket_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventticket",
            old_name="tx_ref",
            new_name="reference",
        ),
    ]
