# Generated by Django 4.2.7 on 2024-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_rename_tx_ref_eventticket_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventticket",
            name="ticket_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
