# Generated by Django 5.1.7 on 2025-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_allowedpaymentmethods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
