# Generated by Django 5.1.7 on 2025-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_eventticket_cancelled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="age_limit",
            field=models.FloatField(default=0, null=True),
        ),
    ]
