services:
  backend:
    build: .
    ports:
      - "8000:8000"
    
  celery:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "worker", "--loglevel=info"]
    depends_on:
      - backend
      

  celery-beat:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "beat", "--loglevel=info"]
    depends_on:
      - backend
      - celery
     