services:
  backend-local:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CURRENT_ENVIRONMENT=LOCAL
      - DEFAULT_FRONTEND_URL=http://localhost:3000
      - DEFAULT_FRONTENT_URL=http://localhost:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    

  celery-local:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "worker", "--loglevel=info"]
    environment:
      - CURRENT_ENVIRONMENT=LOCAL
      - DEFAULT_FRONTEND_URL=http://localhost:3000
      - DEFAULT_FRONTENT_URL=http://localhost:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    depends_on:
      - backend-local
    
      
  celery-beat-local:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "beat", "--loglevel=info"]
    environment:
      - CURRENT_ENVIRONMENT=LOCAL
      - DEFAULT_FRONTEND_URL=http://localhost:3000
      - DEFAULT_FRONTENT_URL=http://localhost:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    depends_on:
      - backend-local
      - celery-local
     