services:
  backend-development:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - CURRENT_ENVIRONMENT=DEVELOPMENT
      - DEFAULT_FRONTEND_URL=http://34.171.61.167:3000
      - DEFAULT_FRONTENT_URL=http://34.171.61.167:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    
  celery-development:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "worker", "--loglevel=info"]
    environment:
      - CURRENT_ENVIRONMENT=DEVELOPMENT
      - DEFAULT_FRONTEND_URL=http://34.171.61.167:3000
      - DEFAULT_FRONTENT_URL=http://34.171.61.167:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    depends_on:
      - backend-development
    
      
  celery-beat-development:
    build: .
    command: ["celery", "-A", "HotelBookingBackend", "beat", "--loglevel=info"]
    environment:
      - CURRENT_ENVIRONMENT=DEVELOPMENT
      - DEFAULT_FRONTEND_URL=http://34.171.61.167:3000
      - DEFAULT_FRONTENT_URL=http://34.171.61.167:8000
      - BROKER_URL=amqp://guest:guest@34.16.123.89:5672
    depends_on:
      - backend-development
      - celery-development