# Generated by Django 4.2.7 on 2023-11-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[("Hotel", "Hotel"), ("AirBnB", "AirBnB"), ("Lodge", "Lodge")],
                max_length=255,
            ),
        ),
    ]
