# Generated by Django 4.2.7 on 2023-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255, unique=True)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], max_length=255)),
                ('occupancy_capacity', models.PositiveIntegerField()),
                ('bed_type', models.CharField(choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('King Size Bed', 'King Size Bed')], max_length=255)),
                ('amenities', models.TextField()),
                ('view', models.CharField(blank=True, choices=[('City View', 'City View'), ('Sea View', 'Sea View'), ('Garden View', 'Garden View')], max_length=255, null=True)),
                ('smoking_room', models.BooleanField(default=False)),
                ('accessibility_features', models.BooleanField(default=False)),
                ('floor_level', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in_time', models.TimeField(null=True)),
                ('check_out_time', models.TimeField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='propertyroom',
            old_name='is_booked',
            new_name='accessibility_features',
        ),
        migrations.RemoveField(
            model_name='propertyroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='propertyroom',
            name='number_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='propertyroom',
            name='number_of_beds',
        ),
        migrations.RemoveField(
            model_name='propertyroom',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='bed_type',
            field=models.CharField(choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('King Size Bed', 'King Size Bed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='floor_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='occupancy_capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='smoking_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='Available', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='view',
            field=models.CharField(blank=True, choices=[('City View', 'City View'), ('Sea View', 'Sea View'), ('Garden View', 'Garden View')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyroom',
            name='amenities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='propertyroom',
            name='room_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyroom',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite')], max_length=255, null=True),
        ),
    ]
