# Generated by Django 4.2.7 on 2023-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_propertyroom_amenities_propertyroom_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyroom',
            name='amenities',
            field=models.JSONField(default=list),
        ),
    ]
