# Generated by Django 4.2.7 on 2023-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertyroom_charge_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyroom',
            name='rooms_number',
            field=models.IntegerField(default=0),
        ),
    ]
