# Generated by Django 4.2.7 on 2023-12-21 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_propertyroom_rooms_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cost",
        ),
    ]
