# Generated by Django 4.2.7 on 2023-12-22 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_remove_property_capacity_remove_property_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyroom",
            name="rooms_count",
        ),
    ]
