# Generated by Django 4.2.7 on 2024-01-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_cost_property_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='property_images/'),
        ),
    ]
