# Generated by Django 4.2.7 on 2024-01-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_property_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
    ]
