# Generated by Django 4.2.7 on 2024-01-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_property_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='adults_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='children_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
