# Generated by Django 4.2.7 on 2024-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
