# Generated by Django 4.2.7 on 2024-01-20 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0018_property_pets_allowed_property_smoking_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listedproperties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
