# Generated by Django 5.1.7 on 2025-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0021_alter_property_amenities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyroom",
            name="booked_dates",
            field=models.JSONField(default=list),
        ),
    ]
