# Generated by Django 5.1.7 on 2025-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0022_propertyroom_booked_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="capacity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
