{
    "event": "charge.success",
    "data": {
        "id": 5056496223,
        "domain": "test",
        "status": "success",
        "reference": "bnb_1_28_1749903004",
        "amount": 2500000,
        "message": None,
        "gateway_response": "Approved",
        "paid_at": "2025-06-14T12:10:38.000Z",
        "created_at": "2025-06-14T12:10:06.000Z",
        "channel": "mobile_money",
        "currency": "KES",
        "ip_address": "105.163.0.196",
        "metadata": {"referrer": "android-app://com.google.android.gm/"},
        "fees_breakdown": None,
        "log": None,
        "fees": 37500,
        "fees_split": None,
        "authorization": {
            "authorization_code": "AUTH_g4bje7g6c9",
            "bin": "071XXX",
            "last4": "X000",
            "exp_month": "12",
            "exp_year": "9999",
            "channel": "mobile_money",
            "card_type": "",
            "bank": "M-PESA",
            "country_code": "KE",
            "brand": "M-pesa",
            "reusable": False,
            "signature": None,
            "account_name": None,
            "receiver_bank_account_number": None,
            "receiver_bank": None,
        },
        "customer": {
            "id": 157742637,
            "first_name": "Paul",
            "last_name": "Ndambo",
            "email": "paulkadabo@gmail.com",
            "customer_code": "CUS_vnx03kgs1vnabri",
            "phone": "0745491093",
            "metadata": {},
            "risk_action": "default",
            "international_format_phone": None,
        },
        "plan": {},
        "subaccount": {},
        "split": {},
        "order_id": None,
        "paidAt": "2025-06-14T12:10:38.000Z",
        "requested_amount": 2500000,
        "pos_transaction_data": None,
        "source": {
            "type": "api",
            "source": "merchant_api",
            "entry_point": "transaction_initialize",
            "identifier": None,
        },
    },
}
