# Generated by Django 4.2.7 on 2023-11-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Deactivated", "Deactivated"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
    ]
