# Generated by Django 4.2.7 on 2023-12-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_eventticket_ticket_type"),
        ("payments", "0002_alter_payment_payment_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventsticketspayments",
                to="events.eventticket",
            ),
        ),
    ]
