# Generated by Django 4.2.7 on 2024-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_serviceproviderwallet_walletlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletlog",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Withdraw", "Withdraw"),
                    ("Refund", "Refund"),
                    ("AirBnB Booking", "AirBnB Booking"),
                    ("Ticket Booking", "Ticket Booking"),
                    ("Room Booking", "Room Booking"),
                    ("Subscription Payment", "Subscription Payment"),
                ],
                max_length=255,
            ),
        ),
    ]
