# Generated by Django 4.2.7 on 2024-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_mpesaresponsebody_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaResponseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_data", models.JSONField(default=dict)),
                ("response_description", models.CharField(max_length=1000)),
                ("response_code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MerchantRequestID", models.CharField(max_length=255, null=True)),
                ("CheckoutRequestID", models.CharField(max_length=255, null=True)),
                ("ResultCode", models.IntegerField(default=0, null=True)),
                ("ResultDesc", models.CharField(max_length=1000, null=True)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TransactionTimeStamp", models.CharField(max_length=255, null=True)),
                ("TransactionDate", models.DateTimeField(null=True)),
                ("PhoneNumber", models.CharField(max_length=255, null=True)),
                ("MpesaReceiptNumber", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="MpesaResponseBody",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
