# Generated by Django 4.2.7 on 2024-02-06 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0011_mpesaresponsedata_mpesatransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaystackPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=500)),
                ("access_code", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=100)),
                ("email", models.EmailField(max_length=254)),
                ("authorization_url", models.URLField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
