# Generated by Django 4.2.7 on 2024-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0012_paystackpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="paystackpayment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
