# Generated by Django 4.2.7 on 2024-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0013_paystackpayment_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="paystackpayment",
            name="payment_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
