# Generated by Django 4.2.7 on 2024-02-06 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0014_paystackpayment_payment_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="tx_ref",
            new_name="reference",
        ),
    ]
