# Generated by Django 4.2.7 on 2024-02-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0015_rename_tx_ref_payment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="paystackpayment",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
    ]
