# Generated by Django 4.2.7 on 2024-02-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0017_rename_tx_ref_bnbbooking_reference_and_more"),
        ("payments", "0016_paystackpayment_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="room_booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.roombooking",
            ),
        ),
    ]
