# Generated by Django 4.2.7 on 2024-02-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0017_rename_tx_ref_bnbbooking_reference_and_more"),
        ("payments", "0017_payment_room_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="event_space_booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventspacebookingpayments",
                to="bookings.eventspacebooking",
            ),
        ),
    ]
