# Generated by Django 4.2.7 on 2024-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0019_alter_payment_payment_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="paystackpayment",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
