# Generated by Django 4.2.7 on 2023-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token_expiration_date",
            field=models.DateTimeField(null=True),
        ),
    ]
