# Generated by Django 4.2.7 on 2023-11-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_activation_date_user_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
