# Generated by Django 4.2.7 on 2023-11-29 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_postion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="postion",
            new_name="position",
        ),
    ]
