# Generated by Django 4.2.7 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_business_address_user_business_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="business_phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
