# Generated by Django 4.2.7 on 2024-02-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_business_email_user_business_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activated",
            field=models.BooleanField(default=True),
        ),
    ]
