# Generated by Django 4.2.7 on 2024-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_activated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activated",
            field=models.BooleanField(default=False),
        ),
    ]
