# Generated by Django 5.1.7 on 2025-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Service Provider', 'Service Provider'), ('customer', 'Customer'), ('staff', 'Staff')], max_length=32, null=True),
        ),
    ]
