# Generated by Django 4.2.7 on 2023-12-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_roombooking_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='payment_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='tx_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
