# Generated by Django 4.2.7 on 2023-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_roombooking_payment_link_roombooking_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
