# Generated by Django 4.2.7 on 2024-01-04 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0006_roombooking_is_over"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roombooking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customerbookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
