# Generated by Django 4.2.7 on 2024-01-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_property_approval_status"),
        ("bookings", "0013_eventspacebooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bnbbooking",
            name="airbnb",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bnbbookings",
                to="property.property",
            ),
        ),
    ]
