# Generated by Django 4.2.7 on 2024-01-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0018_property_pets_allowed_property_smoking_allowed"),
        ("bookings", "0015_alter_eventspacebooking_event_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roombooking",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roombookings",
                to="property.propertyroom",
            ),
        ),
    ]
