# Generated by Django 4.2.7 on 2024-02-06 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0016_alter_roombooking_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bnbbooking",
            old_name="tx_ref",
            new_name="reference",
        ),
        migrations.RenameField(
            model_name="eventspacebooking",
            old_name="tx_ref",
            new_name="reference",
        ),
        migrations.RenameField(
            model_name="roombooking",
            old_name="tx_ref",
            new_name="reference",
        ),
    ]
