# Generated by Django 4.2.7 on 2024-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0017_rename_tx_ref_bnbbooking_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bnbbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Payment", "Pending Payment"),
                    ("Paid", "Paid"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Paying", "Paying"),
                ],
                default="Pending Payment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventspacebooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Payment", "Pending Payment"),
                    ("Paid", "Paid"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Paying", "Paying"),
                ],
                default="Pending Payment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Payment", "Pending Payment"),
                    ("Paid", "Paid"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Paying", "Paying"),
                ],
                default="Pending Payment",
                max_length=255,
                null=True,
            ),
        ),
    ]
