# Generated by Django 5.1.7 on 2025-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_alter_bnbbooking_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="booked_dates",
            field=models.JSONField(default=list),
        ),
    ]
