# Generated by Django 5.1.7 on 2025-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_roombooking_booked_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbbooking',
            name='rooms_booked',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
