# Generated by Django 5.1.7 on 2025-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_bnbbooking_rooms_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbbooking',
            name='days_booked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
