# Generated by Django 5.1.7 on 2025-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0021_alter_bnbbooking_days_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnbbooking",
            name="booked_dates",
            field=models.JSONField(default=list),
        ),
    ]
