# Generated by Django 5.1.7 on 2025-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_eventspacebooking_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspacebooking',
            name='booked_dates',
            field=models.JSONField(default=list),
        ),
    ]
