# Generated by Django 4.2.7 on 2024-01-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("sms", "SMS"), ("email", "email"), ("system", "system")],
                max_length=255,
            ),
        ),
    ]
