# Generated by Django 4.2.7 on 2024-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_message_message_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("subject", models.CharField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
